eureka:
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://39.107.90.67:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: localhost
#    ip-address: 39.108.112.202



