server:
  port: 8761
spring:
  application:
    name: eureka-server
  profiles:
    active: dev
eureka:
  server:
    enable-self-preservation: true
  # 在默认设置下，该服务注册中心也会将自己作为客户端来尝试注册它自己，
  # 禁用客户端注册行为
  client:
    initial-instance-info-replication-interval-seconds: 10
    register-with-eureka: false
    fetch-registry: false
  instance:
    server:
      renewal-percent-threshold: 0.49

